#!/usr/bin/env python

from __future__ import division

import struct
import sys
import threading
import Queue

import subprocess
import shlex

import argparse
import requests
import urlparse

import zipfile

#from slimit.parser import Parser
from pyjsparser.parser import PyJsParser
from HTMLParser import HTMLParser

import os, shutil
from os import walk

try:
	import Tkinter
	import tkMessageBox
except ImportError:
	Tkinter = None

reload(sys)
sys.setdefaultencoding('utf-8')
sys.setrecursionlimit(10000)

# On Windows, the default I/O mode is O_TEXT. Set this to O_BINARY
# to avoid unwanted modifications of the input/output streams.
if sys.platform == "win32":
	import os, msvcrt
	msvcrt.setmode(sys.stdin.fileno(), os.O_BINARY)
	msvcrt.setmode(sys.stdout.fileno(), os.O_BINARY)

# Helper function that sends a message to the webapp.
def send_message(message):
	# Write message size.
	sys.stdout.write(struct.pack('I', len(message)))
	# Write the message itself.
	sys.stdout.write(message)
	sys.stdout.flush()

# Thread that reads messages from the webapp.
def read_thread_func(queue):
	message_number = 0
	while 1:
		# Read the message length (first 4 bytes).
		text_length_bytes = sys.stdin.read(4)

		if len(text_length_bytes) == 0:
			if queue:
				queue.put(None)
			sys.exit(0)

		# Unpack message length as 4 byte integer.
		text_length = struct.unpack('i', text_length_bytes)[0]

		# Read the text (JSON object) of the message.
		text = sys.stdin.read(text_length).decode('utf-8')

		if queue:
			queue.put(text)
		else:
			# In headless mode just send an echo message back.
			send_message('{"echo": %s}' % text)

def dict_generator(indict, pre=None):
	pre = pre[:] if pre else []
	if isinstance(indict, dict):
		for key, value in indict.items():
			if isinstance(value, dict):
				for d in dict_generator(value, pre + [key]):
					yield d
			elif isinstance(value, list) or isinstance(value, tuple):
				for v in value:
					for d in dict_generator(v, pre + [key]):
						yield d
			else:
				yield pre + [key, value]
	else:
		if indict == None:
			yield []
		else:
			yield indict

report = ""

#Static analysis functions:
#URL:
def isURL(s):
	if s.startswith("http://") or s.startswith("https://"):
		return s
	if s[::-1].startswith("http://") or s[::-1].startswith("https://"):
		return "reversed"

	return ""

def check_url(url):
	global report

	#u = urlparse(url)
	spl = url.split('/')
	u = ''.join(spl[2])
	with open("blacklist.txt") as f:
		for line in f:
			if line.strip() == u:
				#report += u+" -- "+line
				return True
	return False

call_list = ["addListener", "onUpdated", "onCreated", "onBeforeRequest", "tabs", "chrome", "remove", "onHeadersReceived", "webRequest", "splice", "install", "management", "uninstall", "webstore", "query", "system", "cpu", "display", "sessions", "getDevices", "XMLHttpRequest", "send"]

dec_list = ["document", "forms"]

elem_list = ["blocking"]

key_list = ["cancel", "redirectUrl"]

#Check for specific calls, variables, elements and keys
def update_calls(i, callees, decs, elems, keys):

	if i.count("callee") > 0 and (i.count("name") > 0 or i.count("value") > 0):
		for c in call_list:
			if i.count(c) > 0:
				callees.append(c)

	elif i.count("declarations") > 0 and (i.count("name") > 0 or i.count("value") > 0):
		for d in dec_list:
			if i.count(d) > 0:
				decs.append(d)

	elif i.count("elements") > 0 and (i.count("name") > 0 or i.count("value") > 0):
		for e in elem_list:
			if i.count(e) > 0:
				elems.append(e)

	elif i.count("key") > 0 and (i.count("name") > 0 or i.count("value") > 0):
		for k in key_list:
			if i.count(k) > 0:
				keys.append(k)

	elif i.count("declarations") > 0 and (i.count("name") > 0 or i.count("value") > 0):
		if i.count("document") >0:
			decs.append("document")
		elif i.count("forms") >0:
			decs.append("forms")

	elif i.count("elements") > 0 and (i.count("name") > 0 or i.count("value") > 0):
		if i.count("blocking") > 0:
			elems.append("blocking")

	elif i.count("key") > 0 and (i.count("name") > 0 or i.count("value") > 0):
		if i.count("cancel") > 0:
			keys.append("cancel")
		if i.count("redirectUrl") > 0:
			keys.append("redirectUrl")

def check_js(tree):
	global report

	CallExpression = []
	callees = []
	Vars = []
	decs = []
	elems = []
	keys = []

	extension_tab = False
	remove_tab = False
	tab_listener = False
	web_listener = False
	security_option = False
	http_header = False
	remove_security = False
	install_extension = False
	uninstall_extension = False
	DoS = False
	cpu = False
	displays = False
	sessions = False
	forms = False
	XMLHttpRequest = False
	send = False
	redirect = False
	cancel = False
	block = False

	l = dict_generator(tree)
	for i in l:
		for j in i:
			#URL:
			url = isURL(str(j).strip())
			if url != "":
				#report += url+"\n"
				if url == "reversed":
					report += "Wanring! URL reversed.\n"
					url = str(j).strip()[::-1]
				if check_url(url):
					report += "Wanring! Blacklisted URL: "+url+"\n"
					#report += report+"\n"
					#report = ""

		k = [str(item).lower() for item in i]

		update_calls(i, callees, decs, elems, keys)
		#Gather call expressions
		if i.count("CallExpression") > 0:
			if callees:
				CallExpression.append(callees)
				callees = []

		#Gather variable declarations
		elif i.count("VariableDeclarator") > 0:
			if decs:
				Vars.append(decs)
				decs = []

		#Check for extension tab
		elif i.count("chrome://chrome/extensions/") > 0 or i.count("chrome://chrome/extensions") > 0 or i.count("chrome://extensions/") > 0 or i.count("chrome://extensions") > 0:
			extension_tab = True

		#Check for security options
		elif k.count("x-frame-options") > 0 or k.count("frame-options") > 0 or k.count("content-security-policy") > 0 or k.count("x-content-security-policy") > 0 or k.count("x-webkit-csp") > 0:
			security_option = True

	if callees:
		CallExpression.append(callees)
		callees = []

	#report += str(CallExpression)+"\n"
	while CallExpression:
		callees = CallExpression.pop()

		# chrome.tabs.onUpdated.addListener / chrome.tabs.onCreated.addListener
		if callees.count("chrome") > 0 and callees.count("tabs") > 0 and (callees.count("onUpdated") > 0 or callees.count("onCreated") > 0) and callees.count("addListener") > 0:
			tab_listener = True

		# chrome.webRequest.onBeforeRequest.addListener
		elif callees.count("chrome") > 0 and callees.count("webRequest") > 0 and callees.count("onBeforeRequest") > 0 and callees.count("addListener") > 0:
			web_listener = True

		#chrome.tabs.remove
		elif callees.count("chrome") > 0 and callees.count("tabs") > 0 and callees.count("remove") > 0:
			remove_tab = True

		#chrome.webRequest.onHeadersReceived.addListener
		elif callees.count("chrome") > 0 and callees.count("webRequest") > 0 and callees.count("onHeadersReceived") > 0 and callees.count("addListener") > 0:
			http_header = True

		#responseHeaders.splice
		elif callees.count("splice") > 0:
			remove_security = True

		#chrome.webstore.install
		elif callees.count("chrome") > 0 and callees.count("webstore") > 0 and callees.count("install") > 0:
			install_extension = True

		#chrome.management.uninstall
		elif callees.count("chrome") > 0 and callees.count("management") > 0 and callees.count("uninstall") > 0:
			uninstall_extension = True

		#chrome.tabs.query
		elif callees.count("chrome") > 0 and callees.count("tabs") > 0 and callees.count("query") > 0:
			DoS = True

		#chrome.system.cpu
		elif callees.count("chrome") > 0 and callees.count("system") > 0 and callees.count("cpu") > 0:
			cpu = True

		#chrome.system.display
		elif callees.count("chrome") > 0 and callees.count("system") > 0 and callees.count("display") > 0:
			displays = True

		#chrome.sessions.getDevices
		elif callees.count("chrome") > 0 and callees.count("sessions") > 0 and callees.count("getDevices") > 0:
			sessions = True

		#new XMLHttpRequest
		elif callees.count("XMLHttpRequest") > 0:
			XMLHttpRequest = True

		#XMLHttpRequest.send
		elif callees.count("send") > 0:
			send = True

	while Vars:
		decs = Vars.pop()

		#document.forms
		if decs.count("document") > 0 and decs.count("forms") > 0:
			forms = True

	for el in elems:
		#["blocking"]
		if el == "blocking":
			block = True

	for k in keys:
		if k == "redirectUrl":
			redirect = True
		elif k == "cancel":
			cancel = True

	#Uninstallation prevention
	if tab_listener and remove_tab and extension_tab:
		report += "Warning! Extension tab blocked.\n"
	#HTTP response header security options
	if http_header and remove_security and security_option:
		report += "Warning! Security options are changed.\n"
	#Extension installation
	if install_extension:
		report += "Warning! Extension installation.\n"
	#Extension uninstallation
	if uninstall_extension:
		report += "Warning! Extension uninstallation.\n"
	#DoS
	if DoS and remove_tab:
		report += "Warning! DoS detected.\n"
	#User's CPU info
	if cpu:
		report += "Warning! User's info monitoring detected (cpu).\n"
	#User's number of displays
	if displays:
		report += "Warning! User's info monitoring detected (displays).\n"
	#User's sessions info
	if sessions:
		report += "Warning! User's info monitoring detected (sessions).\n"
	#Form submit requests
	if forms and XMLHttpRequest and send:
		report += "Warning! Form submit requests leak.\n"
	#Access to websites blocked
	if web_listener and cancel and block:
		report += "Warning! Access to websites blocked.\n"
	#URL MITM
	if web_listener and redirect and block:
		report += "Warning! URL redirection (MITM).\n"

if Tkinter:
	class MyHTMLParser(HTMLParser):
		isScript = False
		def handle_starttag(self, tag, attrs):
			global report
			#tkMessageBox.showinfo( "Start tag:", tag)
			if tag == "script":
				self.isScript = True
				#report += "Start tag: "+tag+"\n"
			#if attrs != None:
			for attr in attrs:
				if attr[1] != None:
					url = isURL(attr[1].strip())
					if url != "":
						if check_url(url):
							report += "Blacklisted URL: "+url+"\n"

		def handle_endtag(self, tag):
			#tkMessageBox.showinfo( "End tag:", tag)
			if tag == "script":
				self.isScript = False

		def handle_data(self, data):
			#tkMessageBox.showinfo( "Data:", data)
			global report
			if self.isScript:
				#report += data+"\n"
				parser = PyJsParser()
				tree = parser.parse(data)

				check_js(tree)
				#self.log(report)

		#def handle_comment(self, data):
			#tkMessageBox.showinfo( "Comment:", data)

		#def handle_entityref(self, name):
			#c = unichr(name2codepoint[name])
			#tkMessageBox.showinfo( "Named ent:", c)

		#def handle_charref(self, name):
			#if name.startswith('x'):
			#    c = unichr(int(name[1:], 16))
			#else:
			#    c = unichr(int(name))
			#tkMessageBox.showinfo( "Num ent:", c)

		#def handle_decl(self, data):
			#tkMessageBox.showinfo( "Decl:", data)

#_____________________________________________________________________

	class NativeMessagingWindow(Tkinter.Frame):
		def __init__(self, queue):
			self.queue = queue

			Tkinter.Frame.__init__(self)
			self.pack()

			self.text = Tkinter.Text(self)
			self.text.grid(row=0, column=0, padx=10, pady=10, columnspan=2)
			self.text.config(state=Tkinter.DISABLED, height=50, width=130)

			self.messageContent = Tkinter.StringVar()

			self.after(100, self.processMessages)

		
		def processMessages(self):
			global report
			while not self.queue.empty():
				self.log("~~~~~~~~~~~~")
				message = self.queue.get_nowait()
				if message == None:
					self.quit()
					return
				self.log("Received %s" % message)

				message = message.replace("\"", "")

				#Download and unzip extension files
				self.log("Downloading Source Code... ")
				self.download(message)
				self.log("Download finished successfully.")

				#List all .js files
				js = []
				html = []
				for (dirpath, dirnames, filenames) in walk('extensions'):
					for filename in filenames:
						if filename[-3:] == '.js':
							path = dirpath+"/"+filename
							js.append(path)
						elif filename[-5:] == '.html':
							path = dirpath+"/"+filename
							html.append(path)

				#tkMessageBox.showinfo('Javascript:', js)
				#tkMessageBox.showinfo('HTML:', html)

				#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
				#Parsing
				#parser = Parser()
				try:
					parser = PyJsParser()
					for jsfile in js:
						self.log("Parsing file "+jsfile+" ...")
						with open(jsfile, 'r') as readfile:
							data = readfile.read().decode('utf-8')
						tree = parser.parse(data)

						check_js(tree)
						self.log(report)

						report = ""
						self.log("File "+jsfile+" parsed successfully.")

					parser2 = MyHTMLParser()
					for htmlfile in html:
						self.log("Parsing file "+htmlfile+" ...")
						with open(htmlfile, 'r') as readfile:
							data = readfile.read().decode('utf-8')
						tree = parser2.feed(data)
						self.log(report)
						self.log("File "+htmlfile+" parsed successfully.")
						#result = tree.to_ecma()
						#tkMessageBox.showinfo('Tree', tree)
						#tkMessageBox.showinfo('Report', report)
						report = ""

				except Exception, e:
					tkMessageBox.showinfo('Application',  e)

				#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

				#Delete extension files
				for the_file in os.listdir('extensions'):
					file_path = os.path.join('extensions', the_file)
					try:
						if os.path.isfile(file_path):
							os.unlink(file_path)
						elif os.path.isdir(file_path): shutil.rmtree(file_path)
					except Exception as e:
						tkMessageBox.showinfo('Application',  e)

				self.log("Finished.")
			self.after(100, self.processMessages)


		def send(self):
			text = "AAAAA"
			self.log('Sending %s' % text)
			try:
				send_message(text)
			except Exception, e:
				tkMessageBox.showinfo('Application',  e)

			#sys.exit(1)

		def log(self, message):
			self.text.config(state=Tkinter.NORMAL)
			self.text.insert(Tkinter.END, message + "\n")
			self.text.config(state=Tkinter.DISABLED)

		def download(self, message):
			try:
				CRX_URL = "https://clients2.google.com/service/update2/crx?" \
				"response=redirect&prodversion=62.0&x=id%3D~~~~%26installsource%3Dondemand%26uc"
				USER_AGENT = "Chrome/62.0.3202.94"
				headers = {
					"User-Agent": USER_AGENT,
					"Referer": "https://chrome.google.com",
				}

				chrome_app_id = message.split("/")[-1]
				chrome_app_id = chrome_app_id.split("?")[0]
				#tkMessageBox.showinfo('Application',  chrome_app_id)
				file_name = message.split("/")[-2]

				download_url = CRX_URL.replace("~~~~", chrome_app_id)

				r = requests.get(url=download_url, headers=headers, stream=True, verify=False)

				redirects = r.history
				_fname_ =""
				if len(redirects) > 0:
					redirect_header = redirects[-1].headers
					if "location" in redirect_header:
						loc = redirect_header["location"]
						uparse = urlparse.urlparse(loc)
						splits = uparse.path.split("/")
						_fname_ = splits[-1]

				if _fname_:
					file_name = _fname_.replace("extension", file_name)
				else:
					file_name += ".crx"

				chunk_size = 16 * 1024
				dowloaded_bytes = 0
				with open(file_name, 'wb') as fd:
					for chunk in r.iter_content(chunk_size):
						fd.write(chunk)

				#Unzip 
				fantasy_zip = zipfile.ZipFile(file_name)
				fantasy_zip.extractall('extensions')
				fantasy_zip.close()

			except Exception, e:
				tkMessageBox.showinfo('Application', e)


def Main():
	if not Tkinter:
		send_message('"Tkinter python module wasn\'t found. Running in headless ' +
					 'mode. Please consider installing Tkinter."')
		read_thread_func(None)
		sys.exit(0)

	queue = Queue.Queue()

	main_window = NativeMessagingWindow(queue)
	main_window.master.title('Application')

	thread = threading.Thread(target=read_thread_func, args=(queue,))
	thread.daemon = True
	thread.start()

	main_window.mainloop()

	sys.exit(0)

if __name__ == '__main__':
	Main()
